2021-05-05 16:44:37,517 | 3778 | proxy.proxy, start_server, 204 | INFO | Server on ('127.0.0.1', 63333)
2021-05-05 16:44:37,517 | 3778 | proxy.proxy, start_server, 207 | INFO | Server serve forever ('127.0.0.1', 63333)
2021-05-05 16:44:44,259 | 3778 | proxy.proxy, handle_switch, 221 | INFO | Client ('127.0.0.1', 33856) is connected
2021-05-05 16:44:44,262 | 3778 | proxy.proxy, handle_switch, 221 | INFO | Client ('127.0.0.1', 33858) is connected
2021-05-05 16:44:44,268 | 3778 | proxy.proxy, handle_switch, 221 | INFO | Client ('127.0.0.1', 33860) is connected
2021-05-05 16:44:44,270 | 3778 | proxy.proxy, handle_switch, 232 | DEBUG | waiting data ......
2021-05-05 16:44:44,279 | 3778 | proxy.proxy, handle_switch, 234 | DEBUG | read b'\x04\x00\x00\x10\x00\x00\x00x\x00\x01\x00\x08\x00\x00\x00\x10'
2021-05-05 16:44:44,280 | 3778 | proxy.proxy, is_closing, 103 | DEBUG | is_closing is False, s writer is True, c writer is True, s handler is True, c handler is True, s writer close? False, c writer close
2021-05-05 16:44:44,280 | 3778 | proxy.proxy, is_closing, 103 | DEBUG | is_closing is False, s writer is True, c writer is True, s handler is True, c handler is True, s writer close? False, c writer close
2021-05-05 16:44:44,280 | 3778 | proxy.proxy, send_to_controller, 72 | WARNING | Failed to send to controller : b'\x04\x00\x00\x10\x00\x00\x00x\x00\x01\x00\x08\x00\x00\x00\x10'
2021-05-05 16:44:44,281 | 3778 | proxy.proxy, handle_switch, 232 | DEBUG | waiting data ......
2021-05-05 16:44:44,281 | 3778 | proxy.proxy, handle_switch, 232 | DEBUG | waiting data ......
2021-05-05 16:44:44,281 | 3778 | proxy.proxy, handle_switch, 234 | DEBUG | read b'\x04\x00\x00\x10\x00\x00\x00y\x00\x01\x00\x08\x00\x00\x00\x10'
2021-05-05 16:44:44,282 | 3778 | proxy.proxy, is_closing, 103 | DEBUG | is_closing is False, s writer is True, c writer is True, s handler is True, c handler is True, s writer close? False, c writer close
2021-05-05 16:44:44,282 | 3778 | proxy.proxy, is_closing, 103 | DEBUG | is_closing is False, s writer is True, c writer is True, s handler is True, c handler is True, s writer close? False, c writer close
2021-05-05 16:44:44,282 | 3778 | proxy.proxy, send_to_controller, 72 | WARNING | Failed to send to controller : b'\x04\x00\x00\x10\x00\x00\x00y\x00\x01\x00\x08\x00\x00\x00\x10'
2021-05-05 16:44:44,283 | 3778 | proxy.proxy, handle_switch, 232 | DEBUG | waiting data ......
2021-05-05 16:44:44,283 | 3778 | proxy.proxy, handle_switch, 232 | DEBUG | waiting data ......
2021-05-05 16:44:44,284 | 3778 | proxy.proxy, handle_switch, 234 | DEBUG | read b'\x04\x00\x00\x10\x00\x00\x00z\x00\x01\x00\x08\x00\x00\x00\x10'
2021-05-05 16:44:44,284 | 3778 | proxy.proxy, is_closing, 103 | DEBUG | is_closing is False, s writer is True, c writer is True, s handler is True, c handler is True, s writer close? False, c writer close
2021-05-05 16:44:44,284 | 3778 | proxy.proxy, is_closing, 103 | DEBUG | is_closing is False, s writer is True, c writer is True, s handler is True, c handler is True, s writer close? False, c writer close
2021-05-05 16:44:44,285 | 3778 | proxy.proxy, send_to_controller, 72 | WARNING | Failed to send to controller : b'\x04\x00\x00\x10\x00\x00\x00z\x00\x01\x00\x08\x00\x00\x00\x10'
2021-05-05 16:44:44,285 | 3778 | proxy.proxy, handle_switch, 232 | DEBUG | waiting data ......
2021-05-05 16:44:44,286 | 3778 | proxy.proxy, handle_controller, 334 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 16:44:44,287 | 3778 | proxy.proxy, handle_controller, 339 | DEBUG | waiting data ......
2021-05-05 16:44:44,288 | 3778 | proxy.proxy, handle_controller, 341 | DEBUG | read b'\x04\x00\x00\x08;@\xd5i'
2021-05-05 16:44:44,288 | 3778 | proxy.proxy, is_closing, 103 | DEBUG | is_closing is False, s writer is True, c writer is True, s handler is True, c handler is True, s writer close? False, c writer close
2021-05-05 16:44:44,289 | 3778 | proxy.proxy, is_closing, 103 | DEBUG | is_closing is False, s writer is True, c writer is True, s handler is True, c handler is True, s writer close? False, c writer close
2021-05-05 16:44:44,295 | 3778 | proxy.proxy, send_to_switch, 90 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08;@\xd5i'
2021-05-05 16:44:44,295 | 3778 | proxy.proxy, handle_controller, 339 | DEBUG | waiting data ......
2021-05-05 16:44:44,296 | 3778 | proxy.proxy, handle_controller, 334 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 16:44:44,296 | 3778 | proxy.proxy, handle_controller, 339 | DEBUG | waiting data ......
2021-05-05 16:44:44,296 | 3778 | proxy.proxy, handle_controller, 341 | DEBUG | read b'\x04\x00\x00\x08\xeef\xe3\xb6'
2021-05-05 16:44:44,297 | 3778 | proxy.proxy, is_closing, 103 | DEBUG | is_closing is False, s writer is True, c writer is True, s handler is True, c handler is True, s writer close? False, c writer close
2021-05-05 16:44:44,297 | 3778 | proxy.proxy, is_closing, 103 | DEBUG | is_closing is False, s writer is True, c writer is True, s handler is True, c handler is True, s writer close? False, c writer close
2021-05-05 16:44:44,297 | 3778 | proxy.proxy, send_to_switch, 90 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08\xeef\xe3\xb6'
2021-05-05 16:44:44,298 | 3778 | proxy.proxy, handle_controller, 339 | DEBUG | waiting data ......
2021-05-05 16:44:44,298 | 3778 | proxy.proxy, handle_controller, 334 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 16:44:44,299 | 3778 | proxy.proxy, handle_controller, 339 | DEBUG | waiting data ......
2021-05-05 16:44:44,299 | 3778 | proxy.proxy, handle_controller, 341 | DEBUG | read b'\x04\x00\x00\x08\xfb\xc5\x99T'
2021-05-05 16:44:44,300 | 3778 | proxy.proxy, is_closing, 103 | DEBUG | is_closing is False, s writer is True, c writer is True, s handler is True, c handler is True, s writer close? False, c writer close
2021-05-05 16:44:44,300 | 3778 | proxy.proxy, is_closing, 103 | DEBUG | is_closing is False, s writer is True, c writer is True, s handler is True, c handler is True, s writer close? False, c writer close
2021-05-05 16:44:44,300 | 3778 | proxy.proxy, send_to_switch, 90 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08\xfb\xc5\x99T'
2021-05-05 16:44:44,301 | 3778 | proxy.proxy, handle_controller, 339 | DEBUG | waiting data ......
2021-05-05 16:44:52,273 | 3778 | proxy.proxy, handle_switch, 234 | DEBUG | read b''
2021-05-05 16:44:52,274 | 3778 | proxy.proxy, handle_switch, 236 | DEBUG | no data from switch read
2021-05-05 16:44:52,275 | 3778 | proxy.proxy, handle_switch, 251 | INFO | Close the connection and do exit processing
2021-05-05 16:44:52,275 | 3778 | proxy.proxy, handle_switch, 234 | DEBUG | read b''
2021-05-05 16:44:52,276 | 3778 | proxy.proxy, handle_switch, 236 | DEBUG | no data from switch read
2021-05-05 16:44:52,277 | 3778 | proxy.proxy, handle_switch, 251 | INFO | Close the connection and do exit processing
2021-05-05 16:44:52,277 | 3778 | proxy.proxy, handle_switch, 234 | DEBUG | read b''
2021-05-05 16:44:52,278 | 3778 | proxy.proxy, handle_switch, 236 | DEBUG | no data from switch read
2021-05-05 16:44:52,278 | 3778 | proxy.proxy, handle_switch, 251 | INFO | Close the connection and do exit processing
2021-05-05 16:44:56,908 | 3778 | root, <module>, 51 | INFO | keyboardInterrupt : 
2021-05-05 16:44:56,915 | 3778 | proxy.proxy, handle_controller, 354 | INFO | Close the connection and do exit processing
2021-05-05 16:44:56,917 | 3778 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-11' coro=<ControllerHandler.handle_controller() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:322> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f4fa01acd90>()]>>
2021-05-05 16:44:56,918 | 3778 | proxy.proxy, handle_controller, 354 | INFO | Close the connection and do exit processing
2021-05-05 16:44:56,918 | 3778 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-12' coro=<ControllerHandler.handle_controller() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:322> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f4fa01acc10>()]>>
2021-05-05 16:44:56,922 | 3778 | proxy.proxy, handle_controller, 354 | INFO | Close the connection and do exit processing
2021-05-05 16:44:56,923 | 3778 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-13' coro=<ControllerHandler.handle_controller() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:322> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f4fa01aca60>()]>>
