2021-05-05 13:53:56,327 | 3482 | proxy.proxy, start_server, 159 | INFO | Server on ('127.0.0.1', 63333)
2021-05-05 13:53:56,328 | 3482 | proxy.proxy, start_server, 162 | INFO | Server serve forever ('127.0.0.1', 63333)
2021-05-05 13:54:00,020 | 3482 | proxy.proxy, handle_switch, 176 | INFO | Client ('127.0.0.1', 45220) is connected
2021-05-05 13:54:00,024 | 3482 | proxy.proxy, handle_switch, 176 | INFO | Client ('127.0.0.1', 45222) is connected
2021-05-05 13:54:00,028 | 3482 | proxy.proxy, handle_switch, 176 | INFO | Client ('127.0.0.1', 45224) is connected
2021-05-05 13:54:00,031 | 3482 | proxy.proxy, handle_controller, 289 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:54:00,038 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:54:00,039 | 3482 | proxy.proxy, handle_controller, 289 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:54:00,040 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:54:00,048 | 3482 | proxy.proxy, handle_controller, 289 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:54:00,049 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:54:00,049 | 3482 | proxy.proxy, handle_controller, 296 | DEBUG | read b'\x04\x00\x00\x08>\xf6\x19r'
2021-05-05 13:54:00,050 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:54:00,050 | 3482 | proxy.proxy, handle_controller, 296 | DEBUG | read b'\x04\x00\x00\x08\x8f=\x1c\xb3'
2021-05-05 13:54:00,052 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:54:00,054 | 3482 | proxy.proxy, handle_controller, 296 | DEBUG | read b'\x04\x00\x00\x08\x97\xdd\xb9\x88'
2021-05-05 13:54:00,055 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:54:16,048 | 3482 | proxy.proxy, handle_switch, 176 | INFO | Client ('127.0.0.1', 45236) is connected
2021-05-05 13:54:16,053 | 3482 | proxy.proxy, handle_controller, 289 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:54:16,058 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:54:16,065 | 3482 | proxy.proxy, handle_controller, 309 | INFO | Close the connection and do exit processing
2021-05-05 13:54:16,068 | 3482 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-8' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:165> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f312f80ae20>()]>>
2021-05-05 13:54:16,069 | 3482 | proxy.proxy, handle_controller, 309 | INFO | Close the connection and do exit processing
2021-05-05 13:54:16,070 | 3482 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-9' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:165> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f312f80adf0>()]>>
2021-05-05 13:54:16,073 | 3482 | proxy.proxy, handle_controller, 309 | INFO | Close the connection and do exit processing
2021-05-05 13:54:16,077 | 3482 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-10' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:165> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f312f80abe0>()]>>
2021-05-05 13:54:16,078 | 3482 | proxy.proxy, handle_controller, 296 | DEBUG | read b'\x04\x00\x00\x08KJ<f'
2021-05-05 13:54:16,078 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:54:16,080 | 3482 | proxy.proxy, handle_switch, 176 | INFO | Client ('127.0.0.1', 45240) is connected
2021-05-05 13:54:16,082 | 3482 | proxy.proxy, handle_switch, 176 | INFO | Client ('127.0.0.1', 45242) is connected
2021-05-05 13:54:16,089 | 3482 | proxy.proxy, handle_controller, 289 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:54:16,090 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:54:16,090 | 3482 | proxy.proxy, handle_controller, 289 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:54:16,091 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:54:16,091 | 3482 | proxy.proxy, handle_controller, 296 | DEBUG | read b'\x04\x00\x00\x08-\x12v\x8f'
2021-05-05 13:54:16,092 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:54:16,092 | 3482 | proxy.proxy, handle_controller, 296 | DEBUG | read b'\x04\x00\x00\x089\x8d\xb3['
2021-05-05 13:54:16,092 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:54:32,077 | 3482 | proxy.proxy, handle_switch, 176 | INFO | Client ('127.0.0.1', 45250) is connected
2021-05-05 13:54:32,085 | 3482 | proxy.proxy, handle_switch, 176 | INFO | Client ('127.0.0.1', 45252) is connected
2021-05-05 13:54:32,095 | 3482 | proxy.proxy, handle_switch, 176 | INFO | Client ('127.0.0.1', 45254) is connected
2021-05-05 13:54:32,097 | 3482 | proxy.proxy, handle_controller, 289 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:54:32,099 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:54:32,104 | 3482 | proxy.proxy, handle_controller, 296 | DEBUG | read b'\x04\x00\x00\x08e(\xad\xcb'
2021-05-05 13:54:32,105 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:54:32,106 | 3482 | proxy.proxy, handle_controller, 289 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:54:32,107 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:54:32,108 | 3482 | proxy.proxy, handle_controller, 289 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:54:32,109 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:54:32,110 | 3482 | proxy.proxy, handle_controller, 296 | DEBUG | read b'\x04\x00\x00\x08L\xd7\t\xb0'
2021-05-05 13:54:32,110 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:54:32,111 | 3482 | proxy.proxy, handle_controller, 296 | DEBUG | read b'\x04\x00\x00\x08\xac\xee;\x91'
2021-05-05 13:54:32,111 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:54:48,106 | 3482 | proxy.proxy, handle_switch, 176 | INFO | Client ('127.0.0.1', 45264) is connected
2021-05-05 13:54:48,110 | 3482 | proxy.proxy, handle_switch, 176 | INFO | Client ('127.0.0.1', 45266) is connected
2021-05-05 13:54:48,111 | 3482 | proxy.proxy, handle_switch, 176 | INFO | Client ('127.0.0.1', 45268) is connected
2021-05-05 13:54:48,113 | 3482 | proxy.proxy, handle_controller, 289 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:54:48,124 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:54:48,125 | 3482 | proxy.proxy, handle_controller, 289 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:54:48,125 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:54:48,125 | 3482 | proxy.proxy, handle_controller, 289 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:54:48,126 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:54:48,126 | 3482 | proxy.proxy, handle_controller, 296 | DEBUG | read b'\x04\x00\x00\x08Q\xd0\xad\xcc'
2021-05-05 13:54:48,127 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:54:48,127 | 3482 | proxy.proxy, handle_controller, 296 | DEBUG | read b'\x04\x00\x00\x08\x08\xb3*e'
2021-05-05 13:54:48,127 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:54:48,128 | 3482 | proxy.proxy, handle_controller, 296 | DEBUG | read b'\x04\x00\x00\x08\x14\x96\xd6\xcf'
2021-05-05 13:54:48,128 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:55:04,154 | 3482 | proxy.proxy, handle_switch, 176 | INFO | Client ('127.0.0.1', 45278) is connected
2021-05-05 13:55:04,159 | 3482 | proxy.proxy, handle_controller, 289 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:55:04,161 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:55:04,161 | 3482 | proxy.proxy, handle_controller, 296 | DEBUG | read b'\x04\x00\x00\x08\x87g\x0c\x02'
2021-05-05 13:55:04,162 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:55:04,163 | 3482 | proxy.proxy, handle_switch, 176 | INFO | Client ('127.0.0.1', 45282) is connected
2021-05-05 13:55:04,165 | 3482 | proxy.proxy, handle_switch, 176 | INFO | Client ('127.0.0.1', 45284) is connected
2021-05-05 13:55:04,173 | 3482 | proxy.proxy, handle_controller, 289 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:55:04,174 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:55:04,174 | 3482 | proxy.proxy, handle_controller, 289 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:55:04,174 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:55:04,175 | 3482 | proxy.proxy, handle_controller, 296 | DEBUG | read b'\x04\x00\x00\x08\x19\xd72z'
2021-05-05 13:55:04,176 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:55:04,176 | 3482 | proxy.proxy, handle_controller, 296 | DEBUG | read b'\x04\x00\x00\x08n\x83\xd8\x8a'
2021-05-05 13:55:04,177 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:55:20,220 | 3482 | proxy.proxy, handle_switch, 176 | INFO | Client ('127.0.0.1', 45294) is connected
2021-05-05 13:55:20,229 | 3482 | proxy.proxy, handle_switch, 176 | INFO | Client ('127.0.0.1', 45298) is connected
2021-05-05 13:55:20,231 | 3482 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-12' coro=<SwitchHandler.handle_switch() running at /home/shu/Network/ofcapture/proxy/proxy.py:180> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f312f80a7c0>()]>>
2021-05-05 13:55:20,240 | 3482 | proxy.proxy, handle_controller, 309 | INFO | Close the connection and do exit processing
2021-05-05 13:55:20,241 | 3482 | proxy.proxy, handle_controller, 309 | INFO | Close the connection and do exit processing
2021-05-05 13:55:20,241 | 3482 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-15' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:165> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f312f80ad90>()]>>
2021-05-05 13:55:20,242 | 3482 | proxy.proxy, handle_controller, 309 | INFO | Close the connection and do exit processing
2021-05-05 13:55:20,242 | 3482 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-16' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:165> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f312f80a790>()]>>
2021-05-05 13:55:20,243 | 3482 | proxy.proxy, handle_controller, 309 | INFO | Close the connection and do exit processing
2021-05-05 13:55:20,243 | 3482 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-18' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:165> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f312f822100>()]>>
2021-05-05 13:55:20,244 | 3482 | proxy.proxy, handle_controller, 309 | INFO | Close the connection and do exit processing
2021-05-05 13:55:20,245 | 3482 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-21' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:165> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f312f8226d0>()]>>
2021-05-05 13:55:20,246 | 3482 | proxy.proxy, handle_controller, 309 | INFO | Close the connection and do exit processing
2021-05-05 13:55:20,247 | 3482 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-22' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:165> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f312f8226a0>()]>>
2021-05-05 13:55:20,248 | 3482 | proxy.proxy, handle_controller, 309 | INFO | Close the connection and do exit processing
2021-05-05 13:55:20,253 | 3482 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-26' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:165> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f312f822eb0>()]>>
2021-05-05 13:55:20,253 | 3482 | proxy.proxy, handle_controller, 309 | INFO | Close the connection and do exit processing
2021-05-05 13:55:20,254 | 3482 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-27' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:165> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f312f822e80>()]>>
2021-05-05 13:55:20,254 | 3482 | proxy.proxy, handle_controller, 309 | INFO | Close the connection and do exit processing
2021-05-05 13:55:20,255 | 3482 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-28' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:165> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f312f822c70>()]>>
2021-05-05 13:55:20,256 | 3482 | proxy.proxy, handle_controller, 309 | INFO | Close the connection and do exit processing
2021-05-05 13:55:20,258 | 3482 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-30' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:165> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f312f7b30d0>()]>>
2021-05-05 13:55:20,260 | 3482 | proxy.proxy, handle_controller, 309 | INFO | Close the connection and do exit processing
2021-05-05 13:55:20,261 | 3482 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-33' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:165> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f312f7b3670>()]>>
2021-05-05 13:55:20,264 | 3482 | proxy.proxy, handle_controller, 309 | INFO | Close the connection and do exit processing
2021-05-05 13:55:20,265 | 3482 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-34' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:165> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f312f7b3640>()]>>
2021-05-05 13:55:20,268 | 3482 | proxy.proxy, handle_switch, 176 | INFO | Client ('127.0.0.1', 45300) is connected
2021-05-05 13:55:20,270 | 3482 | proxy.proxy, handle_controller, 289 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:55:20,272 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:55:20,274 | 3482 | proxy.proxy, handle_controller, 296 | DEBUG | read b'\x04\x00\x00\x08\xc9\x89h\xe6'
2021-05-05 13:55:20,284 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:55:20,286 | 3482 | proxy.proxy, handle_controller, 289 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:55:20,288 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:55:20,289 | 3482 | proxy.proxy, handle_controller, 289 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:55:20,290 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:55:20,291 | 3482 | proxy.proxy, handle_controller, 296 | DEBUG | read b'\x04\x00\x00\x08\x92\x0e\x1aH'
2021-05-05 13:55:20,292 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:55:20,294 | 3482 | proxy.proxy, handle_controller, 296 | DEBUG | read b'\x04\x00\x00\x08\x1f\x18\x85\x19'
2021-05-05 13:55:20,301 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:55:36,265 | 3482 | proxy.proxy, handle_switch, 176 | INFO | Client ('127.0.0.1', 45308) is connected
2021-05-05 13:55:36,266 | 3482 | proxy.proxy, handle_controller, 289 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:55:36,267 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:55:36,269 | 3482 | proxy.proxy, handle_switch, 176 | INFO | Client ('127.0.0.1', 45312) is connected
2021-05-05 13:55:36,274 | 3482 | proxy.proxy, handle_switch, 176 | INFO | Client ('127.0.0.1', 45314) is connected
2021-05-05 13:55:36,276 | 3482 | proxy.proxy, handle_controller, 296 | DEBUG | read b'\x04\x00\x00\x08\xc3\x91\xe9\xc9'
2021-05-05 13:55:36,282 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:55:36,283 | 3482 | proxy.proxy, handle_controller, 289 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:55:36,291 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:55:36,292 | 3482 | proxy.proxy, handle_controller, 289 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:55:36,293 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:55:36,293 | 3482 | proxy.proxy, handle_controller, 296 | DEBUG | read b'\x04\x00\x00\x08\x08\x0c\x87h'
2021-05-05 13:55:36,293 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:55:36,294 | 3482 | proxy.proxy, handle_controller, 296 | DEBUG | read b'\x04\x00\x00\x08\xa0\xfa\xc0\xbb'
2021-05-05 13:55:36,294 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:55:52,300 | 3482 | proxy.proxy, handle_switch, 176 | INFO | Client ('127.0.0.1', 45322) is connected
2021-05-05 13:55:52,308 | 3482 | proxy.proxy, handle_switch, 176 | INFO | Client ('127.0.0.1', 45324) is connected
2021-05-05 13:55:52,313 | 3482 | proxy.proxy, handle_switch, 176 | INFO | Client ('127.0.0.1', 45326) is connected
2021-05-05 13:55:52,318 | 3482 | proxy.proxy, handle_controller, 289 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:55:52,321 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:55:52,324 | 3482 | proxy.proxy, handle_controller, 289 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:55:52,325 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:55:52,325 | 3482 | proxy.proxy, handle_controller, 289 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:55:52,333 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:55:52,334 | 3482 | proxy.proxy, handle_controller, 296 | DEBUG | read b'\x04\x00\x00\x08\x92\x1d1\x98'
2021-05-05 13:55:52,335 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:55:52,339 | 3482 | proxy.proxy, handle_controller, 296 | DEBUG | read b'\x04\x00\x00\x08\xdd\r\x9b\xf5'
2021-05-05 13:55:52,344 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:55:52,346 | 3482 | proxy.proxy, handle_controller, 296 | DEBUG | read b'\x04\x00\x00\x08\xde\x93[/'
2021-05-05 13:55:52,348 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:56:08,321 | 3482 | proxy.proxy, handle_switch, 176 | INFO | Client ('127.0.0.1', 45336) is connected
2021-05-05 13:56:08,328 | 3482 | proxy.proxy, handle_switch, 176 | INFO | Client ('127.0.0.1', 45338) is connected
2021-05-05 13:56:08,331 | 3482 | proxy.proxy, handle_switch, 176 | INFO | Client ('127.0.0.1', 45340) is connected
2021-05-05 13:56:08,335 | 3482 | proxy.proxy, handle_controller, 289 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:56:08,337 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:56:08,338 | 3482 | proxy.proxy, handle_controller, 289 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:56:08,341 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:56:08,342 | 3482 | proxy.proxy, handle_controller, 289 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:56:08,343 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:56:08,344 | 3482 | proxy.proxy, handle_controller, 296 | DEBUG | read b'\x04\x00\x00\x08\x95\x13\x97d'
2021-05-05 13:56:08,347 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:56:08,349 | 3482 | proxy.proxy, handle_controller, 296 | DEBUG | read b'\x04\x00\x00\x08\xe4\xcfA\x8c'
2021-05-05 13:56:08,350 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:56:08,352 | 3482 | proxy.proxy, handle_controller, 296 | DEBUG | read b'\x04\x00\x00\x08<l\x12-'
2021-05-05 13:56:08,354 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:56:24,394 | 3482 | proxy.proxy, handle_switch, 176 | INFO | Client ('127.0.0.1', 45350) is connected
2021-05-05 13:56:24,397 | 3482 | proxy.proxy, handle_switch, 176 | INFO | Client ('127.0.0.1', 45352) is connected
2021-05-05 13:56:24,399 | 3482 | proxy.proxy, handle_switch, 176 | INFO | Client ('127.0.0.1', 45354) is connected
2021-05-05 13:56:24,420 | 3482 | proxy.proxy, handle_controller, 289 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:56:24,429 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:56:24,441 | 3482 | proxy.proxy, handle_controller, 289 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:56:24,442 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:56:24,443 | 3482 | proxy.proxy, handle_controller, 289 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:56:24,448 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:56:24,449 | 3482 | proxy.proxy, handle_controller, 296 | DEBUG | read b'\x04\x00\x00\x08\xc1\x96\x19b'
2021-05-05 13:56:24,450 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:56:24,450 | 3482 | proxy.proxy, handle_controller, 296 | DEBUG | read b'\x04\x00\x00\x08\xf9\xf7\xe9\x18'
2021-05-05 13:56:24,451 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:56:24,451 | 3482 | proxy.proxy, handle_controller, 296 | DEBUG | read b'\x04\x00\x00\x08\x1cN&\xa8'
2021-05-05 13:56:24,452 | 3482 | proxy.proxy, handle_controller, 294 | DEBUG | waiting data ......
2021-05-05 13:56:30,856 | 3482 | root, <module>, 51 | INFO | keyboardInterrupt : 
2021-05-05 13:56:30,865 | 3482 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-39' coro=<SwitchHandler.handle_switch() running at /home/shu/Network/ofcapture/proxy/proxy.py:180> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f312f822520>()]>>
2021-05-05 13:56:30,868 | 3482 | proxy.proxy, handle_controller, 309 | INFO | Close the connection and do exit processing
2021-05-05 13:56:30,870 | 3482 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-40' coro=<SwitchHandler.handle_switch() running at /home/shu/Network/ofcapture/proxy/proxy.py:180> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f312f822a30>()]>>
2021-05-05 13:56:30,871 | 3482 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-36' coro=<SwitchHandler.handle_switch() running at /home/shu/Network/ofcapture/proxy/proxy.py:180> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f312f822cd0>()]>>
2021-05-05 13:56:30,872 | 3482 | proxy.proxy, handle_controller, 309 | INFO | Close the connection and do exit processing
2021-05-05 13:56:30,873 | 3482 | proxy.proxy, handle_controller, 309 | INFO | Close the connection and do exit processing
2021-05-05 13:56:30,873 | 3482 | proxy.proxy, handle_controller, 309 | INFO | Close the connection and do exit processing
2021-05-05 13:56:30,874 | 3482 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-42' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:165> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f312f822d30>()]>>
2021-05-05 13:56:30,877 | 3482 | proxy.proxy, handle_controller, 309 | INFO | Close the connection and do exit processing
2021-05-05 13:56:30,878 | 3482 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-45' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:165> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f312f8225b0>()]>>
2021-05-05 13:56:30,879 | 3482 | proxy.proxy, handle_controller, 309 | INFO | Close the connection and do exit processing
2021-05-05 13:56:30,881 | 3482 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-46' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:165> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f312f822be0>()]>>
2021-05-05 13:56:30,883 | 3482 | proxy.proxy, handle_controller, 309 | INFO | Close the connection and do exit processing
2021-05-05 13:56:30,889 | 3482 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-50' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:165> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f312f80ac40>()]>>
2021-05-05 13:56:30,890 | 3482 | proxy.proxy, handle_controller, 309 | INFO | Close the connection and do exit processing
2021-05-05 13:56:30,890 | 3482 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-51' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:165> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f312f80adc0>()]>>
2021-05-05 13:56:30,891 | 3482 | proxy.proxy, handle_controller, 309 | INFO | Close the connection and do exit processing
2021-05-05 13:56:30,895 | 3482 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-52' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:165> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f312f80aac0>()]>>
2021-05-05 13:56:30,896 | 3482 | proxy.proxy, handle_controller, 309 | INFO | Close the connection and do exit processing
2021-05-05 13:56:30,900 | 3482 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-56' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:165> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f312f7b3340>()]>>
2021-05-05 13:56:30,900 | 3482 | proxy.proxy, handle_controller, 309 | INFO | Close the connection and do exit processing
2021-05-05 13:56:30,901 | 3482 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-57' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:165> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f312f7b3220>()]>>
2021-05-05 13:56:30,903 | 3482 | proxy.proxy, handle_controller, 309 | INFO | Close the connection and do exit processing
2021-05-05 13:56:30,903 | 3482 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-58' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:165> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f312f7b37c0>()]>>
2021-05-05 13:56:30,904 | 3482 | proxy.proxy, handle_controller, 309 | INFO | Close the connection and do exit processing
2021-05-05 13:56:30,905 | 3482 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-62' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:165> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f312f7b31f0>()]>>
2021-05-05 13:56:30,905 | 3482 | proxy.proxy, handle_controller, 309 | INFO | Close the connection and do exit processing
2021-05-05 13:56:30,906 | 3482 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-63' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:165> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f312f7b3d30>()]>>
2021-05-05 13:56:30,907 | 3482 | proxy.proxy, handle_controller, 309 | INFO | Close the connection and do exit processing
2021-05-05 13:56:30,908 | 3482 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-64' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:165> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f312f7b3ca0>()]>>
