2021-05-05 09:05:05,341 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:05:05,342 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:05:05,343 | 17871 | proxy.proxy, start_server, 132 | INFO | Server on ('127.0.0.1', 63333)
2021-05-05 09:05:05,343 | 17871 | proxy.proxy, start_server, 135 | INFO | Server serve forever ('127.0.0.1', 63333)
2021-05-05 09:05:10,343 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:05:10,343 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:05:15,345 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:05:15,348 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:05:20,352 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:05:20,352 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:05:25,356 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:05:25,356 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:05:30,362 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:05:30,362 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:05:35,364 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:05:35,364 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:05:37,480 | 17871 | proxy.proxy, handle_switch, 149 | INFO | Client ('127.0.0.1', 59925) is connected
2021-05-05 09:05:37,480 | 17871 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 09:05:37,480 | 17871 | proxy.proxy, handle_switch, 157 | DEBUG | read b's0'
2021-05-05 09:05:37,481 | 17871 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 09:05:38,482 | 17871 | proxy.proxy, handle_switch, 149 | INFO | Client ('127.0.0.1', 59926) is connected
2021-05-05 09:05:38,482 | 17871 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 09:05:38,482 | 17871 | proxy.proxy, handle_switch, 157 | DEBUG | read b's1'
2021-05-05 09:05:38,483 | 17871 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 09:05:39,485 | 17871 | proxy.proxy, handle_switch, 149 | INFO | Client ('127.0.0.1', 59927) is connected
2021-05-05 09:05:39,486 | 17871 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 09:05:39,486 | 17871 | proxy.proxy, handle_switch, 157 | DEBUG | read b's2'
2021-05-05 09:05:39,487 | 17871 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 09:05:40,369 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:05:40,369 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:05:40,490 | 17871 | proxy.proxy, handle_switch, 149 | INFO | Client ('127.0.0.1', 59929) is connected
2021-05-05 09:05:40,490 | 17871 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 09:05:40,490 | 17871 | proxy.proxy, handle_switch, 157 | DEBUG | read b's3'
2021-05-05 09:05:40,490 | 17871 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 09:05:41,494 | 17871 | proxy.proxy, handle_switch, 149 | INFO | Client ('127.0.0.1', 59930) is connected
2021-05-05 09:05:41,495 | 17871 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 09:05:41,495 | 17871 | proxy.proxy, handle_switch, 157 | DEBUG | read b's4'
2021-05-05 09:05:41,496 | 17871 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 09:05:42,496 | 17871 | proxy.proxy, handle_switch, 149 | INFO | Client ('127.0.0.1', 59931) is connected
2021-05-05 09:05:42,496 | 17871 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 09:05:42,497 | 17871 | proxy.proxy, handle_switch, 157 | DEBUG | read b's5'
2021-05-05 09:05:42,497 | 17871 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 09:05:43,497 | 17871 | proxy.proxy, handle_switch, 149 | INFO | Client ('127.0.0.1', 59932) is connected
2021-05-05 09:05:43,497 | 17871 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 09:05:43,498 | 17871 | proxy.proxy, handle_switch, 157 | DEBUG | read b's6'
2021-05-05 09:05:43,498 | 17871 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 09:05:44,499 | 17871 | proxy.proxy, handle_switch, 149 | INFO | Client ('127.0.0.1', 59933) is connected
2021-05-05 09:05:44,499 | 17871 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 09:05:44,500 | 17871 | proxy.proxy, handle_switch, 157 | DEBUG | read b's7'
2021-05-05 09:05:44,500 | 17871 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 09:05:45,371 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:05:45,372 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:05:45,500 | 17871 | proxy.proxy, handle_switch, 149 | INFO | Client ('127.0.0.1', 59939) is connected
2021-05-05 09:05:45,500 | 17871 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 09:05:45,500 | 17871 | proxy.proxy, handle_switch, 157 | DEBUG | read b's8'
2021-05-05 09:05:45,500 | 17871 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 09:05:46,500 | 17871 | proxy.proxy, handle_switch, 149 | INFO | Client ('127.0.0.1', 59940) is connected
2021-05-05 09:05:46,501 | 17871 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 09:05:46,501 | 17871 | proxy.proxy, handle_switch, 157 | DEBUG | read b's9'
2021-05-05 09:05:46,501 | 17871 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 09:05:50,377 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:05:50,377 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:05:55,380 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:05:55,381 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:06:00,382 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:06:00,383 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:06:05,385 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:06:05,385 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:06:10,391 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:06:10,391 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:06:15,393 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:06:15,394 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:06:20,400 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:06:20,400 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:06:25,403 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:06:25,404 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:06:30,409 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:06:30,409 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:06:35,410 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:06:35,410 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:06:40,412 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:06:40,413 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:06:45,415 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:06:45,416 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:06:49,507 | 17871 | proxy.proxy, handle_switch, 157 | DEBUG | read b''
2021-05-05 09:06:49,519 | 17871 | proxy.proxy, handle_switch, 159 | DEBUG | no data from switch read
2021-05-05 09:06:49,520 | 17871 | proxy.proxy, handle_switch, 170 | INFO | Close the connection and do exit processing
2021-05-05 09:06:49,521 | 17871 | proxy.proxy, handle_switch, 157 | DEBUG | read b''
2021-05-05 09:06:49,522 | 17871 | proxy.proxy, handle_switch, 159 | DEBUG | no data from switch read
2021-05-05 09:06:49,522 | 17871 | proxy.proxy, handle_switch, 170 | INFO | Close the connection and do exit processing
2021-05-05 09:06:49,523 | 17871 | proxy.proxy, handle_switch, 157 | DEBUG | read b''
2021-05-05 09:06:49,523 | 17871 | proxy.proxy, handle_switch, 159 | DEBUG | no data from switch read
2021-05-05 09:06:49,523 | 17871 | proxy.proxy, handle_switch, 170 | INFO | Close the connection and do exit processing
2021-05-05 09:06:49,524 | 17871 | proxy.proxy, handle_switch, 157 | DEBUG | read b''
2021-05-05 09:06:49,524 | 17871 | proxy.proxy, handle_switch, 159 | DEBUG | no data from switch read
2021-05-05 09:06:49,524 | 17871 | proxy.proxy, handle_switch, 170 | INFO | Close the connection and do exit processing
2021-05-05 09:06:49,524 | 17871 | proxy.proxy, handle_switch, 157 | DEBUG | read b''
2021-05-05 09:06:49,525 | 17871 | proxy.proxy, handle_switch, 159 | DEBUG | no data from switch read
2021-05-05 09:06:49,525 | 17871 | proxy.proxy, handle_switch, 170 | INFO | Close the connection and do exit processing
2021-05-05 09:06:49,525 | 17871 | proxy.proxy, handle_switch, 157 | DEBUG | read b''
2021-05-05 09:06:49,526 | 17871 | proxy.proxy, handle_switch, 159 | DEBUG | no data from switch read
2021-05-05 09:06:49,526 | 17871 | proxy.proxy, handle_switch, 170 | INFO | Close the connection and do exit processing
2021-05-05 09:06:49,526 | 17871 | proxy.proxy, handle_switch, 157 | DEBUG | read b''
2021-05-05 09:06:49,527 | 17871 | proxy.proxy, handle_switch, 159 | DEBUG | no data from switch read
2021-05-05 09:06:49,527 | 17871 | proxy.proxy, handle_switch, 170 | INFO | Close the connection and do exit processing
2021-05-05 09:06:49,527 | 17871 | proxy.proxy, handle_switch, 157 | DEBUG | read b''
2021-05-05 09:06:49,528 | 17871 | proxy.proxy, handle_switch, 159 | DEBUG | no data from switch read
2021-05-05 09:06:49,528 | 17871 | proxy.proxy, handle_switch, 170 | INFO | Close the connection and do exit processing
2021-05-05 09:06:49,529 | 17871 | proxy.proxy, handle_switch, 157 | DEBUG | read b''
2021-05-05 09:06:49,529 | 17871 | proxy.proxy, handle_switch, 159 | DEBUG | no data from switch read
2021-05-05 09:06:49,529 | 17871 | proxy.proxy, handle_switch, 170 | INFO | Close the connection and do exit processing
2021-05-05 09:06:49,530 | 17871 | proxy.proxy, handle_switch, 157 | DEBUG | read b''
2021-05-05 09:06:49,530 | 17871 | proxy.proxy, handle_switch, 159 | DEBUG | no data from switch read
2021-05-05 09:06:49,530 | 17871 | proxy.proxy, handle_switch, 170 | INFO | Close the connection and do exit processing
2021-05-05 09:06:50,417 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:06:50,418 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:06:55,421 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:06:55,422 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:07:00,423 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:07:00,423 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:07:05,429 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:07:05,429 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:07:10,432 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:07:10,432 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:07:15,433 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:07:15,434 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:07:20,438 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:07:20,439 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:07:25,442 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:07:25,443 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:07:30,448 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:07:30,449 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:07:35,453 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:07:35,453 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:07:40,456 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:07:40,456 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:07:45,458 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:07:45,459 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:07:50,464 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:07:50,464 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:07:55,467 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:07:55,467 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:08:00,469 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:08:00,469 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:08:05,474 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:08:05,475 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:08:10,480 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:08:10,480 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:08:15,485 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:08:15,486 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:08:20,492 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:08:20,492 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:08:25,495 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:08:25,495 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:08:30,501 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:08:30,501 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:08:35,505 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:08:35,505 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:08:40,507 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:08:40,508 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:08:45,509 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:08:45,510 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:08:50,515 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:08:50,516 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:08:55,521 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:08:55,521 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:09:00,525 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:09:00,525 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:09:05,532 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:09:05,532 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:09:10,536 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:09:10,536 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:09:15,538 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:09:15,538 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:09:20,542 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:09:20,542 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:09:25,547 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:09:25,547 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:09:30,549 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:09:30,550 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:09:35,553 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:09:35,553 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:09:40,558 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:09:40,558 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:09:45,562 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:09:45,562 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:09:50,566 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:09:50,567 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:09:55,569 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:09:55,569 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:10:00,571 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:10:00,571 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:10:05,577 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:10:05,577 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:10:10,585 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:10:10,585 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:10:15,591 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:10:15,592 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:10:20,598 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:10:20,598 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:10:25,600 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:10:25,600 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:10:30,603 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:10:30,604 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:10:35,608 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:10:35,608 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:10:40,614 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:10:40,614 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:10:45,617 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:10:45,619 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:10:50,621 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:10:50,621 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:10:55,624 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:10:55,624 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:11:00,627 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:11:00,629 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:11:05,638 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:11:05,638 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:11:10,684 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:11:10,708 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:11:15,713 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:11:15,713 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:11:20,719 | 17871 | proxy.proxy, open_connection, 242 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 09:11:20,722 | 17871 | proxy.proxy, open_connection, 248 | DEBUG | reconnect to controller a few seconds later
2021-05-05 09:11:24,918 | 17871 | root, <module>, 53 | INFO | keyboardInterrupt : 
