2021-05-05 13:58:18,928 | 3506 | proxy.proxy, start_server, 166 | INFO | Server on ('127.0.0.1', 63333)
2021-05-05 13:58:18,928 | 3506 | proxy.proxy, start_server, 169 | INFO | Server serve forever ('127.0.0.1', 63333)
2021-05-05 13:58:23,428 | 3506 | proxy.proxy, handle_switch, 183 | INFO | Client ('127.0.0.1', 45466) is connected
2021-05-05 13:58:23,431 | 3506 | proxy.proxy, handle_switch, 183 | INFO | Client ('127.0.0.1', 45468) is connected
2021-05-05 13:58:23,434 | 3506 | proxy.proxy, handle_switch, 183 | INFO | Client ('127.0.0.1', 45470) is connected
2021-05-05 13:58:23,445 | 3506 | proxy.proxy, handle_controller, 296 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:58:23,446 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:58:23,446 | 3506 | proxy.proxy, handle_controller, 296 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:58:23,447 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:58:23,447 | 3506 | proxy.proxy, handle_controller, 296 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:58:23,447 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:58:23,448 | 3506 | proxy.proxy, handle_controller, 303 | DEBUG | read b"\x04\x00\x00\x08'k\x07\x9b"
2021-05-05 13:58:23,448 | 3506 | proxy.proxy, send_to_switch, 63 | WARNING | Failed to send to switch : b"\x04\x00\x00\x08'k\x07\x9b"
2021-05-05 13:58:23,449 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:58:23,449 | 3506 | proxy.proxy, handle_controller, 303 | DEBUG | read b'\x04\x00\x00\x086 \xf8\x97'
2021-05-05 13:58:23,450 | 3506 | proxy.proxy, send_to_switch, 63 | WARNING | Failed to send to switch : b'\x04\x00\x00\x086 \xf8\x97'
2021-05-05 13:58:23,450 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:58:23,451 | 3506 | proxy.proxy, handle_controller, 303 | DEBUG | read b'\x04\x00\x00\x08\xd9{\xb9\x9a'
2021-05-05 13:58:23,451 | 3506 | proxy.proxy, send_to_switch, 63 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08\xd9{\xb9\x9a'
2021-05-05 13:58:23,451 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:58:39,578 | 3506 | proxy.proxy, handle_controller, 316 | INFO | Close the connection and do exit processing
2021-05-05 13:58:39,578 | 3506 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-8' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:172> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f6c98236df0>()]>>
2021-05-05 13:58:39,579 | 3506 | proxy.proxy, handle_controller, 316 | INFO | Close the connection and do exit processing
2021-05-05 13:58:39,579 | 3506 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-9' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:172> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f6c98236dc0>()]>>
2021-05-05 13:58:39,580 | 3506 | proxy.proxy, handle_controller, 316 | INFO | Close the connection and do exit processing
2021-05-05 13:58:39,580 | 3506 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-10' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:172> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f6c98236bb0>()]>>
2021-05-05 13:58:39,581 | 3506 | proxy.proxy, handle_switch, 183 | INFO | Client ('127.0.0.1', 45484) is connected
2021-05-05 13:58:39,584 | 3506 | proxy.proxy, handle_switch, 183 | INFO | Client ('127.0.0.1', 45486) is connected
2021-05-05 13:58:39,597 | 3506 | proxy.proxy, handle_switch, 183 | INFO | Client ('127.0.0.1', 45488) is connected
2021-05-05 13:58:39,598 | 3506 | proxy.proxy, handle_controller, 296 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:58:39,600 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:58:39,601 | 3506 | proxy.proxy, handle_controller, 296 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:58:39,601 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:58:39,602 | 3506 | proxy.proxy, handle_controller, 296 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:58:39,603 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:58:39,606 | 3506 | proxy.proxy, handle_controller, 303 | DEBUG | read b'\x04\x00\x00\x08\x1e4\xa2\xd9'
2021-05-05 13:58:39,608 | 3506 | proxy.proxy, send_to_switch, 63 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08\x1e4\xa2\xd9'
2021-05-05 13:58:39,610 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:58:39,616 | 3506 | proxy.proxy, handle_controller, 303 | DEBUG | read b'\x04\x00\x00\x08,\n\xf3A'
2021-05-05 13:58:39,616 | 3506 | proxy.proxy, send_to_switch, 63 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08,\n\xf3A'
2021-05-05 13:58:39,617 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:58:39,617 | 3506 | proxy.proxy, handle_controller, 303 | DEBUG | read b'\x04\x00\x00\x08$\xd7\x84W'
2021-05-05 13:58:39,617 | 3506 | proxy.proxy, send_to_switch, 63 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08$\xd7\x84W'
2021-05-05 13:58:39,618 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:58:55,659 | 3506 | proxy.proxy, handle_switch, 183 | INFO | Client ('127.0.0.1', 45498) is connected
2021-05-05 13:58:55,913 | 3506 | proxy.proxy, handle_switch, 183 | INFO | Client ('127.0.0.1', 45500) is connected
2021-05-05 13:58:55,923 | 3506 | proxy.proxy, handle_switch, 183 | INFO | Client ('127.0.0.1', 45502) is connected
2021-05-05 13:58:56,215 | 3506 | proxy.proxy, handle_controller, 296 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:58:56,221 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:58:56,222 | 3506 | proxy.proxy, handle_controller, 296 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:58:56,223 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:58:56,224 | 3506 | proxy.proxy, handle_controller, 296 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:58:56,227 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:58:56,228 | 3506 | proxy.proxy, handle_controller, 303 | DEBUG | read b'\x04\x00\x00\x08A\x8f\xdb5'
2021-05-05 13:58:56,229 | 3506 | proxy.proxy, send_to_switch, 63 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08A\x8f\xdb5'
2021-05-05 13:58:56,230 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:58:56,230 | 3506 | proxy.proxy, handle_controller, 303 | DEBUG | read b'\x04\x00\x00\x08\xbb#\xf0\xf2'
2021-05-05 13:58:56,230 | 3506 | proxy.proxy, send_to_switch, 63 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08\xbb#\xf0\xf2'
2021-05-05 13:58:56,232 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:58:56,232 | 3506 | proxy.proxy, handle_controller, 303 | DEBUG | read b'\x04\x00\x00\x08\xf4\xb47\xf2'
2021-05-05 13:58:56,233 | 3506 | proxy.proxy, send_to_switch, 63 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08\xf4\xb47\xf2'
2021-05-05 13:58:56,234 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:59:11,730 | 3506 | proxy.proxy, handle_switch, 183 | INFO | Client ('127.0.0.1', 45512) is connected
2021-05-05 13:59:11,735 | 3506 | proxy.proxy, handle_switch, 183 | INFO | Client ('127.0.0.1', 45514) is connected
2021-05-05 13:59:11,738 | 3506 | proxy.proxy, handle_switch, 183 | INFO | Client ('127.0.0.1', 45516) is connected
2021-05-05 13:59:11,748 | 3506 | proxy.proxy, handle_controller, 296 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:59:11,752 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:59:11,753 | 3506 | proxy.proxy, handle_controller, 296 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:59:11,753 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:59:11,753 | 3506 | proxy.proxy, handle_controller, 296 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:59:11,754 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:59:11,755 | 3506 | proxy.proxy, handle_controller, 303 | DEBUG | read b'\x04\x00\x00\x08~\xe0\xa8\xbe'
2021-05-05 13:59:11,756 | 3506 | proxy.proxy, send_to_switch, 63 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08~\xe0\xa8\xbe'
2021-05-05 13:59:11,756 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:59:11,760 | 3506 | proxy.proxy, handle_controller, 303 | DEBUG | read b'\x04\x00\x00\x08\x97\xa0\xaeZ'
2021-05-05 13:59:11,761 | 3506 | proxy.proxy, send_to_switch, 63 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08\x97\xa0\xaeZ'
2021-05-05 13:59:11,761 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:59:11,762 | 3506 | proxy.proxy, handle_controller, 303 | DEBUG | read b'\x04\x00\x00\x08\xa2\xc3\xc4\xc8'
2021-05-05 13:59:11,762 | 3506 | proxy.proxy, send_to_switch, 63 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08\xa2\xc3\xc4\xc8'
2021-05-05 13:59:11,763 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:59:27,755 | 3506 | proxy.proxy, handle_switch, 183 | INFO | Client ('127.0.0.1', 45526) is connected
2021-05-05 13:59:27,763 | 3506 | proxy.proxy, handle_switch, 183 | INFO | Client ('127.0.0.1', 45528) is connected
2021-05-05 13:59:27,765 | 3506 | proxy.proxy, handle_switch, 183 | INFO | Client ('127.0.0.1', 45530) is connected
2021-05-05 13:59:27,769 | 3506 | proxy.proxy, handle_controller, 296 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:59:27,769 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:59:27,770 | 3506 | proxy.proxy, handle_controller, 296 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:59:27,770 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:59:27,771 | 3506 | proxy.proxy, handle_controller, 296 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:59:27,771 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:59:27,772 | 3506 | proxy.proxy, handle_controller, 303 | DEBUG | read b'\x04\x00\x00\x08\xbc\x82gM'
2021-05-05 13:59:27,773 | 3506 | proxy.proxy, send_to_switch, 63 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08\xbc\x82gM'
2021-05-05 13:59:27,773 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:59:27,774 | 3506 | proxy.proxy, handle_controller, 303 | DEBUG | read b'\x04\x00\x00\x08\x96r\xeb\xf4'
2021-05-05 13:59:27,774 | 3506 | proxy.proxy, send_to_switch, 63 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08\x96r\xeb\xf4'
2021-05-05 13:59:27,775 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:59:27,775 | 3506 | proxy.proxy, handle_controller, 303 | DEBUG | read b'\x04\x00\x00\x08%s\xc0T'
2021-05-05 13:59:27,776 | 3506 | proxy.proxy, send_to_switch, 63 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08%s\xc0T'
2021-05-05 13:59:27,776 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:59:43,782 | 3506 | proxy.proxy, handle_switch, 183 | INFO | Client ('127.0.0.1', 45540) is connected
2021-05-05 13:59:43,786 | 3506 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-14' coro=<SwitchHandler.handle_switch() running at /home/shu/Network/ofcapture/proxy/proxy.py:187> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f6c98236ca0>()]>>
2021-05-05 13:59:43,797 | 3506 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-15' coro=<SwitchHandler.handle_switch() running at /home/shu/Network/ofcapture/proxy/proxy.py:187> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f6c98236880>()]>>
2021-05-05 13:59:43,798 | 3506 | proxy.proxy, handle_controller, 316 | INFO | Close the connection and do exit processing
2021-05-05 13:59:43,798 | 3506 | proxy.proxy, handle_controller, 316 | INFO | Close the connection and do exit processing
2021-05-05 13:59:43,799 | 3506 | proxy.proxy, handle_controller, 316 | INFO | Close the connection and do exit processing
2021-05-05 13:59:43,799 | 3506 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-16' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:172> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f6c98236580>()]>>
2021-05-05 13:59:43,804 | 3506 | proxy.proxy, handle_controller, 316 | INFO | Close the connection and do exit processing
2021-05-05 13:59:43,804 | 3506 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-20' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:172> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f6c9824f6a0>()]>>
2021-05-05 13:59:43,805 | 3506 | proxy.proxy, handle_controller, 316 | INFO | Close the connection and do exit processing
2021-05-05 13:59:43,805 | 3506 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-21' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:172> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f6c9824f670>()]>>
2021-05-05 13:59:43,805 | 3506 | proxy.proxy, handle_controller, 316 | INFO | Close the connection and do exit processing
2021-05-05 13:59:43,806 | 3506 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-22' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:172> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f6c9824f460>()]>>
2021-05-05 13:59:43,806 | 3506 | proxy.proxy, handle_controller, 316 | INFO | Close the connection and do exit processing
2021-05-05 13:59:43,807 | 3506 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-26' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:172> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f6c9824fe80>()]>>
2021-05-05 13:59:43,807 | 3506 | proxy.proxy, handle_controller, 316 | INFO | Close the connection and do exit processing
2021-05-05 13:59:43,808 | 3506 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-27' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:172> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f6c9824fe50>()]>>
2021-05-05 13:59:43,808 | 3506 | proxy.proxy, handle_controller, 316 | INFO | Close the connection and do exit processing
2021-05-05 13:59:43,809 | 3506 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-28' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:172> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f6c9824fc40>()]>>
2021-05-05 13:59:43,810 | 3506 | proxy.proxy, handle_controller, 316 | INFO | Close the connection and do exit processing
2021-05-05 13:59:43,811 | 3506 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-32' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:172> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f6c981e06a0>()]>>
2021-05-05 13:59:43,812 | 3506 | proxy.proxy, handle_controller, 316 | INFO | Close the connection and do exit processing
2021-05-05 13:59:43,812 | 3506 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-33' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:172> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f6c981e0670>()]>>
2021-05-05 13:59:43,813 | 3506 | proxy.proxy, handle_controller, 316 | INFO | Close the connection and do exit processing
2021-05-05 13:59:43,816 | 3506 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-34' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:172> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f6c981e0460>()]>>
2021-05-05 13:59:43,817 | 3506 | proxy.proxy, handle_switch, 183 | INFO | Client ('127.0.0.1', 45542) is connected
2021-05-05 13:59:43,819 | 3506 | proxy.proxy, handle_switch, 183 | INFO | Client ('127.0.0.1', 45544) is connected
2021-05-05 13:59:43,834 | 3506 | proxy.proxy, handle_controller, 296 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:59:43,842 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:59:43,843 | 3506 | proxy.proxy, handle_controller, 296 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:59:43,847 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:59:43,848 | 3506 | proxy.proxy, handle_controller, 296 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:59:43,849 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:59:43,850 | 3506 | proxy.proxy, handle_controller, 303 | DEBUG | read b'\x04\x00\x00\x08\xb6\x85\xd8\x9e'
2021-05-05 13:59:43,850 | 3506 | proxy.proxy, send_to_switch, 63 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08\xb6\x85\xd8\x9e'
2021-05-05 13:59:43,850 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:59:43,855 | 3506 | proxy.proxy, handle_controller, 303 | DEBUG | read b'\x04\x00\x00\x08=\x1c\x91\x9d'
2021-05-05 13:59:43,856 | 3506 | proxy.proxy, send_to_switch, 63 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08=\x1c\x91\x9d'
2021-05-05 13:59:43,857 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:59:43,857 | 3506 | proxy.proxy, handle_controller, 303 | DEBUG | read b'\x04\x00\x00\x08Z7\xe1\x8b'
2021-05-05 13:59:43,858 | 3506 | proxy.proxy, send_to_switch, 63 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08Z7\xe1\x8b'
2021-05-05 13:59:43,858 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:59:59,807 | 3506 | proxy.proxy, handle_switch, 183 | INFO | Client ('127.0.0.1', 45554) is connected
2021-05-05 13:59:59,816 | 3506 | proxy.proxy, handle_switch, 183 | INFO | Client ('127.0.0.1', 45556) is connected
2021-05-05 13:59:59,817 | 3506 | proxy.proxy, handle_switch, 183 | INFO | Client ('127.0.0.1', 45558) is connected
2021-05-05 13:59:59,823 | 3506 | proxy.proxy, handle_controller, 296 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:59:59,831 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:59:59,833 | 3506 | proxy.proxy, handle_controller, 303 | DEBUG | read b'\x04\x00\x00\x08fj\x93H'
2021-05-05 13:59:59,834 | 3506 | proxy.proxy, send_to_switch, 63 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08fj\x93H'
2021-05-05 13:59:59,834 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:59:59,835 | 3506 | proxy.proxy, handle_controller, 296 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:59:59,835 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:59:59,836 | 3506 | proxy.proxy, handle_controller, 296 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 13:59:59,836 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:59:59,837 | 3506 | proxy.proxy, handle_controller, 303 | DEBUG | read b'\x04\x00\x00\x08\xfb\x99\xec\xdb'
2021-05-05 13:59:59,837 | 3506 | proxy.proxy, send_to_switch, 63 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08\xfb\x99\xec\xdb'
2021-05-05 13:59:59,838 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 13:59:59,838 | 3506 | proxy.proxy, handle_controller, 303 | DEBUG | read b'\x04\x00\x00\x08\xe7\xab\xbc\x0c'
2021-05-05 13:59:59,839 | 3506 | proxy.proxy, send_to_switch, 63 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08\xe7\xab\xbc\x0c'
2021-05-05 13:59:59,842 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 14:00:15,833 | 3506 | proxy.proxy, handle_switch, 183 | INFO | Client ('127.0.0.1', 45568) is connected
2021-05-05 14:00:15,837 | 3506 | proxy.proxy, handle_switch, 183 | INFO | Client ('127.0.0.1', 45570) is connected
2021-05-05 14:00:15,840 | 3506 | proxy.proxy, handle_switch, 183 | INFO | Client ('127.0.0.1', 45572) is connected
2021-05-05 14:00:15,842 | 3506 | proxy.proxy, handle_controller, 296 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 14:00:15,851 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 14:00:15,852 | 3506 | proxy.proxy, handle_controller, 303 | DEBUG | read b'\x04\x00\x00\x08\x85\xbb\xbe\xe6'
2021-05-05 14:00:15,852 | 3506 | proxy.proxy, send_to_switch, 63 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08\x85\xbb\xbe\xe6'
2021-05-05 14:00:15,853 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 14:00:15,853 | 3506 | proxy.proxy, handle_controller, 296 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 14:00:15,854 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 14:00:15,855 | 3506 | proxy.proxy, handle_controller, 296 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 14:00:15,856 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 14:00:15,856 | 3506 | proxy.proxy, handle_controller, 303 | DEBUG | read b'\x04\x00\x00\x08J\xca\xd9\xbe'
2021-05-05 14:00:15,857 | 3506 | proxy.proxy, send_to_switch, 63 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08J\xca\xd9\xbe'
2021-05-05 14:00:15,858 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 14:00:15,858 | 3506 | proxy.proxy, handle_controller, 303 | DEBUG | read b'\x04\x00\x00\x089\x9e\xde\xfa'
2021-05-05 14:00:15,859 | 3506 | proxy.proxy, send_to_switch, 63 | WARNING | Failed to send to switch : b'\x04\x00\x00\x089\x9e\xde\xfa'
2021-05-05 14:00:15,860 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 14:00:31,861 | 3506 | proxy.proxy, handle_switch, 183 | INFO | Client ('127.0.0.1', 45582) is connected
2021-05-05 14:00:31,876 | 3506 | proxy.proxy, handle_switch, 183 | INFO | Client ('127.0.0.1', 45584) is connected
2021-05-05 14:00:31,884 | 3506 | proxy.proxy, handle_switch, 183 | INFO | Client ('127.0.0.1', 45586) is connected
2021-05-05 14:00:31,886 | 3506 | proxy.proxy, handle_controller, 296 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 14:00:31,889 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 14:00:31,890 | 3506 | proxy.proxy, handle_controller, 303 | DEBUG | read b'\x04\x00\x00\x08om\xcfa'
2021-05-05 14:00:31,890 | 3506 | proxy.proxy, send_to_switch, 63 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08om\xcfa'
2021-05-05 14:00:31,891 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 14:00:31,891 | 3506 | proxy.proxy, handle_controller, 296 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 14:00:31,892 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 14:00:31,893 | 3506 | proxy.proxy, handle_controller, 296 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 14:00:31,893 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 14:00:31,896 | 3506 | proxy.proxy, handle_controller, 303 | DEBUG | read b'\x04\x00\x00\x08\xa3B\x9bx'
2021-05-05 14:00:31,897 | 3506 | proxy.proxy, send_to_switch, 63 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08\xa3B\x9bx'
2021-05-05 14:00:31,897 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 14:00:31,897 | 3506 | proxy.proxy, handle_controller, 303 | DEBUG | read b'\x04\x00\x00\x08\xdd\xe6\xb2\xe4'
2021-05-05 14:00:31,898 | 3506 | proxy.proxy, send_to_switch, 63 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08\xdd\xe6\xb2\xe4'
2021-05-05 14:00:31,898 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 14:00:47,886 | 3506 | proxy.proxy, handle_switch, 183 | INFO | Client ('127.0.0.1', 45596) is connected
2021-05-05 14:00:47,890 | 3506 | proxy.proxy, handle_switch, 183 | INFO | Client ('127.0.0.1', 45598) is connected
2021-05-05 14:00:47,893 | 3506 | proxy.proxy, handle_switch, 183 | INFO | Client ('127.0.0.1', 45600) is connected
2021-05-05 14:00:47,900 | 3506 | proxy.proxy, handle_controller, 296 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 14:00:47,900 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 14:00:47,906 | 3506 | proxy.proxy, handle_controller, 303 | DEBUG | read b'\x04\x00\x00\x08;J\x17\xc9'
2021-05-05 14:00:47,906 | 3506 | proxy.proxy, send_to_switch, 63 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08;J\x17\xc9'
2021-05-05 14:00:47,907 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 14:00:47,908 | 3506 | proxy.proxy, handle_controller, 296 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 14:00:47,908 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 14:00:47,909 | 3506 | proxy.proxy, handle_controller, 296 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 14:00:47,909 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 14:00:47,910 | 3506 | proxy.proxy, handle_controller, 303 | DEBUG | read b'\x04\x00\x00\x08\xa9]\xe0\x8f'
2021-05-05 14:00:47,911 | 3506 | proxy.proxy, send_to_switch, 63 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08\xa9]\xe0\x8f'
2021-05-05 14:00:47,911 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 14:00:47,912 | 3506 | proxy.proxy, handle_controller, 303 | DEBUG | read b'\x04\x00\x00\x08DA\xf8\x19'
2021-05-05 14:00:47,915 | 3506 | proxy.proxy, send_to_switch, 63 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08DA\xf8\x19'
2021-05-05 14:00:47,915 | 3506 | proxy.proxy, handle_controller, 301 | DEBUG | waiting data ......
2021-05-05 14:01:02,886 | 3506 | root, <module>, 51 | INFO | keyboardInterrupt : 
2021-05-05 14:01:02,901 | 3506 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-38' coro=<SwitchHandler.handle_switch() running at /home/shu/Network/ofcapture/proxy/proxy.py:187> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f6c9824f940>()]>>
2021-05-05 14:01:02,904 | 3506 | proxy.proxy, handle_controller, 316 | INFO | Close the connection and do exit processing
2021-05-05 14:01:02,906 | 3506 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-39' coro=<SwitchHandler.handle_switch() running at /home/shu/Network/ofcapture/proxy/proxy.py:187> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f6c9824f250>()]>>
2021-05-05 14:01:02,907 | 3506 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-40' coro=<SwitchHandler.handle_switch() running at /home/shu/Network/ofcapture/proxy/proxy.py:187> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f6c9824fcd0>()]>>
2021-05-05 14:01:02,908 | 3506 | proxy.proxy, handle_controller, 316 | INFO | Close the connection and do exit processing
2021-05-05 14:01:02,908 | 3506 | proxy.proxy, handle_controller, 316 | INFO | Close the connection and do exit processing
2021-05-05 14:01:02,909 | 3506 | proxy.proxy, handle_controller, 316 | INFO | Close the connection and do exit processing
2021-05-05 14:01:02,913 | 3506 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-42' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:172> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f6c9824f6a0>()]>>
2021-05-05 14:01:02,914 | 3506 | proxy.proxy, handle_controller, 316 | INFO | Close the connection and do exit processing
2021-05-05 14:01:02,921 | 3506 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-45' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:172> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f6c9824f0a0>()]>>
2021-05-05 14:01:02,923 | 3506 | proxy.proxy, handle_controller, 316 | INFO | Close the connection and do exit processing
2021-05-05 14:01:02,925 | 3506 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-46' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:172> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f6c9824f700>()]>>
2021-05-05 14:01:02,931 | 3506 | proxy.proxy, handle_controller, 316 | INFO | Close the connection and do exit processing
2021-05-05 14:01:02,932 | 3506 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-48' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:172> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f6c982367c0>()]>>
2021-05-05 14:01:02,933 | 3506 | proxy.proxy, handle_controller, 316 | INFO | Close the connection and do exit processing
2021-05-05 14:01:02,937 | 3506 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-51' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:172> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f6c98236ee0>()]>>
2021-05-05 14:01:02,938 | 3506 | proxy.proxy, handle_controller, 316 | INFO | Close the connection and do exit processing
2021-05-05 14:01:02,938 | 3506 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-52' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:172> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f6c98236d30>()]>>
2021-05-05 14:01:02,940 | 3506 | proxy.proxy, handle_controller, 316 | INFO | Close the connection and do exit processing
2021-05-05 14:01:02,942 | 3506 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-54' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:172> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f6c98236d60>()]>>
2021-05-05 14:01:02,949 | 3506 | proxy.proxy, handle_controller, 316 | INFO | Close the connection and do exit processing
2021-05-05 14:01:02,957 | 3506 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-57' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:172> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f6c981e0040>()]>>
2021-05-05 14:01:02,958 | 3506 | proxy.proxy, handle_controller, 316 | INFO | Close the connection and do exit processing
2021-05-05 14:01:02,960 | 3506 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-58' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:172> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f6c981e06a0>()]>>
2021-05-05 14:01:02,962 | 3506 | proxy.proxy, handle_controller, 316 | INFO | Close the connection and do exit processing
2021-05-05 14:01:02,971 | 3506 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-60' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:172> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f6c981e0610>()]>>
2021-05-05 14:01:02,972 | 3506 | proxy.proxy, handle_controller, 316 | INFO | Close the connection and do exit processing
2021-05-05 14:01:02,973 | 3506 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-63' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:172> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f6c981e0e50>()]>>
2021-05-05 14:01:02,974 | 3506 | proxy.proxy, handle_controller, 316 | INFO | Close the connection and do exit processing
2021-05-05 14:01:02,975 | 3506 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-64' coro=<SwitchHandler.handle_switch() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:172> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f6c981e0c70>()]>>
